#  pulsechain-specific configuration file.
# testnet 943 wss://rpc.v4.testnet.pulsechain.com
# mainnet 369 wss://rpc-pulsechain.g4mm4.io wss://rpc.pulsechain.com

web3j:
  node:
    url: wss://rpc.v4.testnet.pulsechain.com
    chainId: 943
    pollingInterval: 2000
    # This has to be a valid key for a valid address for reading.
    # We use a well-known address from the hardhat test environment.
    # This is not a secret and can be safely used here.
    readerKey: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

logging:
  level:
    root: error
    org:
      web3j:
        protocol: info
    com:
      betterbank: info


groundskeeper:
  mintRedeemer: "0xfe8f43EceFc0E90EC7cA8b95Cc22Aa716F47B4Ba"
  treasuries: "0x766Cbe8Bee1a6Bc5b15502fea2011683A402F3eC,0x0Bc190F650f5e90baA5b719ea337B4931e7781d3,0xdD725808BC332d4eB43d6Db89C6A02D7887aECBb"
  # private key for the executor account.  use a low-value key, as this can be compromised.  can be supplied via environment
  executor: "0xc40cd7f910a2a64db0eb01900dc38be1fb2fef256ed573be4eae832b2b1d9281"
